name: Auto-merge Dependabot PRs after CI

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Wait for check-runs to pass
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const ref = pr.head.sha;

            const { data } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref,
            });

            const failed = data.check_runs.some(run => run.conclusion !== 'success');
            const pending = data.check_runs.some(run => run.status !== 'completed');

            if (failed) {
              core.setFailed('Some check runs failed.');
            } else if (pending) {
              core.setFailed('Some check runs are still pending.');
            }

      - name: Merge the PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              merge_method: "squash"
            });
