name: Build

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="/root/.bun/bin:$PATH"

      - name: Install Dependencies
        run: bun install

      - name: Build Project
        run: bun run build

      - name: Commit and Push Build Outputs
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "[WF]: Build"
          git push
