name: Update Dependencies

on:
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install npm-check-updates temporarily
        run: bun add -d npm-check-updates

      - name: Run npm-check-updates to upgrade package.json
        run: bunx ncu -u

      - name: Install updated dependencies
        run: bun install --force

      - name: Commit and Push Updates
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add package.json bun.lock
          if ! git diff-index --quiet HEAD; then
            git commit -m "[WF]: Updated dependencies via ncu"
            git pull --rebase origin main
            git push
          else
            echo "No dependency updates"
          fi
